### ISSUE TITLE
Problem with save/load

### ISSUE THREAD

**Issue by riedgar-ms** [microsoft/responsible-ai-toolbox#1046]
I'm having trouble saving a previously loaded ModelAnalysis object. It throws an exception.

Specifically, I'm following the notebook responsibleaitoolbox-classification-model-assessment.ipynb in our examples.

After the cell:
```python
dashboard_pipeline = Pipeline(steps=[('preprocess', feat_pipe), ('model', model)])

model_analysis = ModelAnalysis(dashboard_pipeline, train_data_sample, test_data_sample, target_feature, 'classification',
                               categorical_features=categorical_features)
```
I do
```python
model_analysis.save("my_model_analysis")
ma_2 = ModelAnalysis.load("my_model_analysis")

ma_2.causal.add(treatment_features=["age", "gender"], heterogeneity_features=['marital-status'])
ma_2.compute()
```
Then I attempt to save this:
```python
ma_2.save("added_causal")
```
The last line results in an error:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-11-c622ea5a6644> in <module>
----> 1 ma_2.save("added_causal")

c:\users\riedgar\source\repos\responsible-ai-widgets\responsibleai\responsibleai\modelanalysis\model_analysis.py in save(self, path)
    161         :type path: str
    162         """
--> 163         self.rai_insights.save(path)
    164 
    165     @staticmethod

c:\users\riedgar\source\repos\responsible-ai-widgets\responsibleai\responsibleai\rai_insights\rai_insights.py in save(self, path)
    506         # save each of the individual managers
    507         for manager in self._managers:
--> 508             manager._save(top_dir / manager.name)
    509         # save current state
    510         data_directory = Path(path) / _DATA

c:\users\riedgar\source\repos\responsible-ai-widgets\responsibleai\responsibleai\_managers\explainer_manager.py in _save(self, path)
    308 
    309         # save the explanation
--> 310         if self._explanation:
    311             save_explanation(self._explanation,
    312                              data_directory / ManagerNames.EXPLAINER)

AttributeError: 'ExplainerManager' object has no attribute '_explanation'
```

I've checked that I can still use the original object:
```python
model_analysis.causal.add(treatment_features=["age", "gender"], heterogeneity_features=['marital-status'])
model_analysis.compute()
model_analysis.save("second_save_from_original_object")
```
and everything still works.

**Comment by riedgar-ms** [comment]
I've done some digging, and the problem is almost certainly coming from the `_load()` method of the `ExplanationManager`. [Specifically](https://github.com/microsoft/responsible-ai-widgets/blob/76b7c0637ba0646e12d2c90573f19f6267817496/responsibleai/responsibleai/_managers/explainer_manager.py#L346):
```python
        if explanation_path.exists():
            explanation = load_explanation(explanation_path)
            inst.__dict__[EXPLANATION] = explanation
```
So if there's no explanation, then `self._explanation` won't even exist. Compare this to the constructor which sets `self._explanation = None`.

However, this version of `ExplanationManager` is still built for only a single explanation..... AIUI one of @gaugup 's currently pending PRs addresses this

**Comment by imatiach-msft** [comment]
Strange, it seems like this code hasn't changed in a while.  I wonder if it is an existing issue and not an old issue, but then I'm not sure how the notebook was ever passing.  Maybe the notebook is missing from our test scripts.

**Comment by imatiach-msft** [comment]
After more inspection, it sounds like this is indeed an old issue, and there should be (hopefully!) a simple fix for it.  It doesn't seem to be a breaking change with the new 0.15 release.

**Comment by gaugup** [comment]
@riedgar-ms giving the repro steps a try. Will try to have a fix and the test out in a bit. What scenario is being tested here? multiple saves followed by load and save again?

**Comment by riedgar-ms** [comment]
@gaugup I'm going to have a PR out in a couple of minutes. This is coming up with DPv2. The original component saves, the tool component loads, does its work, and then saves
