### ISSUE TITLE
Loaded Explanations can't be resaved

### ISSUE THREAD

**Issue by riedgar-ms** [microsoft/responsible-ai-toolbox#1081]
Repro:

1. Add explantion to `RAIInsights`
2. Save to disk
3. Load the explanation
4. Try to save again

Result is an exception:
```
./responsibleai/tests/test_rai_insights.py::TestRAIInsights::test_rai_insights_add_save_load_save[explainer] Failed: [undefined]AttributeError: 'list' object has no attribute 'tolist'
```

Branch which adds test for this:
https://github.com/microsoft/responsible-ai-toolbox/tree/riedgar-ms/load-save-testing

**Comment by gaugup** [comment]
This needs a fix in interpret-community which is addressed by the PR https://github.com/interpretml/interpret-community/pull/470. We would need a new interpret-community release and then integrate it in responsibleai.
