### ISSUE TITLE
[ResponsibleAIDashboard]: Heatmap cannot get generated for int64 features

### ISSUE THREAD

**Issue by nushib** [microsoft/responsible-ai-toolbox#1091]
Notebook: http://localhost:8888/notebooks/responsibleaidashboard-housing-classification-model-debugging.ipynb

Generate heatmap using "OverallCond" as feature1

Error: 
ERROR in app: Exception on /matrix [POST]
...
TypeError: Object of type 'int64' is not JSON serializable

**Comment by imatiach-msft** [comment]
closing as fixed with PR https://github.com/microsoft/responsible-ai-toolbox/pull/1097
