### ISSUE TITLE
[WhatIf Counterfactuals] Error when changing feature values

### ISSUE THREAD

**Issue by calathea21** [microsoft/responsible-ai-toolbox#1138]
I would like to run some WhatIf analysis on the Census dataset, to see whether changing the sex of people has an effect on the prediction probabilities for a high income. However, I feel like there's a bug somewhere in the code. When I make a copy of a 'female' instance, and change their 'sex' to male, this neither has an effect on the prediction probability nor on the displayed 'sex' of the copy:

![image](https://user-images.githubusercontent.com/81799614/149519744-b2b54535-184e-4ba3-9fdf-a0b987f142e2.png)
(here "Copy of 330" is the copy of instance 330, but with their sex changed to 'male'. The prediction probability is the same as before, and also the sex is still displayed as 'female').

To compare I also tried the effect of changing a persons' education level on their prediction probability:
![image](https://user-images.githubusercontent.com/81799614/149520157-6ef41ca5-56d7-4a8d-bb85-caf4f600d39f.png)
Here the red point is a copy of the blue point, but with the education level switched from '9' to '13'. Here the change in education level is clearly displayed and we can also see a change in prediction probability. This is what led me to think that there's some kind of bug when computing the effect of changing 'sex'. 

I appreciate any help on this :)

**Comment by imatiach-msft** [comment]
@calathea21 I think this is because we use a lightgbm model with just 5 estimators:
```
clf = LGBMClassifier(n_estimators=5)
```
this is to make sure that it makes a lot of errors.
But, it has the effect that you saw, where not all variables are used.
Perhaps it makes more sense to use fewer estimators even though the error results might not be as interesting.

**Comment by imatiach-msft** [comment]
Actually, it seems when we make the changes to categorical values we don't send a predict call, so I think you're right.  Looks like something in the UI logic needs to be fixed for the dropdowns.

**Comment by imatiach-msft** [comment]
closing as this has been fixed with PR #1225
