### ISSUE TITLE
RAIInsights Causal - Heterogeneity Model unclear

### ISSUE THREAD

**Issue by riedgar-ms** [microsoft/responsible-ai-toolbox#1140]
It is not clear what the valid values are for the `heterogeneity_model` argument to the Causal manager. Seeing the definition in the code:
```python
        heterogeneity_model: str = ModelTypes.LINEAR,
```
I assumed that anything from `ModelTypes` would work:
```python
class ModelTypes:
    """Model type constants."""
    AUTOML = 'automl'
    LINEAR = 'linear'
```
However, I've just had an error back from running the manager:
```
[stderr]  File "create_causal.py", line 117, in <module>
[stderr]    main(args)
[stderr]  File "create_causal.py", line 75, in main
[stderr]    rai_i.causal.add(
[stderr]  File "/azureml-envs/azureml_831cf987908ea38a7b7c810bd17d4c02/lib/python3.8/site-packages/responsibleai/_managers/causal_manager.py", line 184, in add
[stderr]    self._fit_causal_analysis(analysis, X_train, y_train,
[stderr]  File "/azureml-envs/azureml_831cf987908ea38a7b7c810bd17d4c02/lib/python3.8/site-packages/responsibleai/_managers/causal_manager.py", line 257, in _fit_causal_analysis
[stderr]    causal_analysis.fit(X, y)
[stderr]  File "/azureml-envs/azureml_831cf987908ea38a7b7c810bd17d4c02/lib/python3.8/site-packages/econml/solutions/causal_analysis/_causal_analysis.py", line 644, in fit
[stderr]    assert self.heterogeneity_model in ['linear', 'forest'], (
[stderr]AssertionError: The only supported heterogeneity models are 'linear' and 'forest' but received automl
```
I'm going to fix my component, but at the very least the docstring should list the valid values.

**Comment by gaugup** [comment]
I have updated the linked PR with the relevant doc strings. @riedgar-ms could you take a look?

**Comment by riedgar-ms** [comment]
It's good to see the allowed values listed, but it would also be helpful to have a line as to what 'heterogeneity' and 'nuisance' features are. I know that the docstrings aren't for in-depth discussion, but it would be good to give a one line explanation as to what those are about.

**Comment by gaugup** [comment]
So I talked to the econml maintainer. The nuisance model tries to estimate the treatment features and the outcome variable from the other features in the data. 

The heterogeneity model  helps to estimate the treatment effect based on the heterogeneity features.

The econml maintainer will add better doc strings for these in econml package. I can then bring those details in our responsibleai package.
