### ISSUE TITLE
RAIInsights Counterfactual - desired_range for random and kdtree

### ISSUE THREAD

**Issue by riedgar-ms** [microsoft/responsible-ai-toolbox#1150]
I've just discovered that the desired_range argument is handled differently when `model=random` and `model=kdtree`.

I'm working on a classification problem with the DPv2 components, and those default `desired_range` to being an empty list. With `model=random` everything works fine. However, `model=kdtree` I get an error due to an extra check which is made when `desired_range` is not `None`. This is happening [here](https://github.com/interpretml/DiCE/blob/e6a1dc3893799a364da993d4a368b7ccfabe4447/dice_ml/explainer_interfaces/dice_KD.py#L92).

I'm going to adjust my component to fix this, but these two cases really should be treated the same for both models. Either an empty list should work for both for `desired_range` or it should fail for both.

**Comment by gaugup** [comment]
The desired_range parameter should be None in classification scenario and not an empty list. This is as per the signature of the method of generate_counterfactuals() at https://github.com/interpretml/DiCE/blob/e6a1dc3893799a364da993d4a368b7ccfabe4447/dice_ml/explainer_interfaces/explainer_base.py#L49. Can you try setting desired_range as None for both random and kdtree explainers?

I don't think there is anything to fix in responsibleai or diceml. Is that understanding correct?

**Comment by riedgar-ms** [comment]
If it should be `None` in a classification scenario, then why is an empty list acceptable when the `model=random` ?

**Comment by gaugup** [comment]
It might be a bug in dice_random.py but certainly desired_range should be None for classification scenario. I will probably add a validation in dice-ml to catch that condition.

**Comment by gaugup** [comment]
Closing this issue as the PR in dice-ml is merged.
