### ISSUE TITLE
Failed to generate json tree representation:name 'Index' is not defined

### ISSUE THREAD

**Issue by tongyu-microsoft** [microsoft/responsible-ai-toolbox#1152]
For cohort filter 'Index', when we add an Index filter, and switch cohort, the /tree call returns error: `error: "Failed to generate json tree representation:name 'Index' is not defined"`. Same issue for /matrix call.
![image](https://user-images.githubusercontent.com/91754176/150074559-ca7abe06-b655-4532-a3b4-324a6af04ecf.png)
![image](https://user-images.githubusercontent.com/91754176/150074582-71519cb1-f332-4240-a1f2-e0f8f2e7c452.png)

**Comment by imatiach-msft** [comment]
closing as PR https://github.com/microsoft/responsible-ai-toolbox/pull/1160 has been merged
