### ISSUE TITLE
 HTTP ERROR 403

### ISSUE THREAD

**Issue by Harikantipudi** [microsoft/responsible-ai-toolbox#1288]
Not sure if its just me but getting HTTP ERROR 403 " You don't have authorization to view this page "

I am using a MacPro and running a sample notebook and trying to get into local host

http://localhost:5000/

**Comment by gaugup** [comment]
@Harikantipudi, which version of raiwidgets are you running? I have not heard of any such issues with viewing of the dashboard. Maybe restarting your machine may help if you are running into some permissions issues.

Regards,

**Comment by gaugup** [comment]
Closing this issue as no response from the submitter.
