### ISSUE TITLE
Pip install in main readme

### ISSUE THREAD

**Issue by FlorianPydde** [microsoft/responsible-ai-toolbox#1309]
Can you please add the pip command or link to the latest package version in the main Readme? The "Getting start" notebook doesn't have it.

**Comment by imatiach-msft** [comment]
@FlorianPydde I think the getting-started notebook (https://github.com/microsoft/responsible-ai-toolbox/blob/main/notebooks/responsibleaidashboard/getting-started.ipynb) does have the pip install command:

![image](https://user-images.githubusercontent.com/24683184/161297854-3de9445f-21fa-4d72-82c1-535d976c83d6.png)

However, it's a good idea to add this command to the main readme as well.

**Comment by imatiach-msft** [comment]
closing as fixed with PR:
https://github.com/microsoft/responsible-ai-toolbox/pull/1320
