### ISSUE TITLE
Causal Analysis getting stuck

### ISSUE THREAD

**Issue by riedgar-ms** [microsoft/responsible-ai-toolbox#1430]
This appears to be related to the latest release of SciKit-Learn 1.1.0. I've found that causal analysis can get stuck under certain circumstances. Using a debugger, this appears to happen inside SciKit-Learn's tree estimators, but I've not managed to dissect it much more than that. It was found in the RAI component testing.

For a repo case, see PR #1429

**Comment by gaugup** [comment]
closing this issue as the related PRs have merged.
