### ISSUE TITLE
Data Explorer chart does not render when count is on the Y axis

### ISSUE THREAD

**Issue by jamescarpinter** [microsoft/responsible-ai-toolbox#1453]
Repo instructions:
1. Install the latest `raiwidgets` package (0.18.2).
2. Run either Housing sample notebook (`$/notebooks/responsibleaidashboard/responsibleaidashboard-housing-decision-making.ipynb` or `$/notebooks/responsibleaidashboard/responsibleaidashboard-housing-classification-model-debugging.ipynb`).
3. Run the notebook and open the link to the dashboard once available.
4. In the Data Explorer panel, change the Y-axis to "Count".
5. Observe the graph is no longer visible. Switching to other Y axis values still show the graph.

This worked as expected in v0.17.

**Comment by imatiach-msft** [comment]
closing as PR https://github.com/microsoft/responsible-ai-toolbox/pull/1454 has been merged
