### ISSUE TITLE
Release new PyPI versions with LICENSE as part of distribution

### ISSUE THREAD

**Issue by janjagusch** [microsoft/responsible-ai-toolbox#1543]
Following up on @imatiach-msft's [comment](https://github.com/microsoft/responsible-ai-toolbox/pull/1522#issuecomment-1175303331), it would be great if you could make a new release for the following packages, now the license and the requirements are parts of the source distribution.

- rai-core-flask
- raiutils

All other packages already seem to have a new release.

Thanks a lot in advance!

**Comment by imatiach-msft** [comment]
closing issue as new version of raiutils (https://pypi.org/project/raiutils/0.2.0/) and rai-core-flask (https://pypi.org/project/rai-core-flask/0.4.0/) have been released.  I will also work on releasing new versions of raiwidgets and responsibleai packages that will depend on these newly released packages.
