### ISSUE TITLE
Tree Map: error rate / error coverage equal for every node

### ISSUE THREAD

**Issue by gbayomi** [microsoft/responsible-ai-toolbox#1594]
**Describe the bug**
Running through the example notebooks (wine/breast cancer), the tree map shows the same value error value for all nodes.

**To Reproduce**

1. Run the ErrorAnalysisDashboard for any classification task under the example notebooks.

**Expected behavior**
It's expected to show different values for each node.

**Screenshots**

<img width="780" alt="Screen Shot 2022-07-28 at 6 21 07 PM" src="https://user-images.githubusercontent.com/5874830/181663189-99cd749b-75b1-417d-9725-50741ba59dea.png">

**Desktop (please complete the following information):**

- OS: MacOS Big Sur
- Browser: Chrome (Jupyter Notebook)
- Python version: 3.7.13
- raiwidgets and responsibleai package versions: 0.20.0

**Comment by imatiach-msft** [comment]
@gbayomi yes sorry, I broke it with the 0.3.5 pypi release of erroranalysis package 2 days ago:
https://pypi.org/project/erroranalysis/0.3.5/#history
I already fixed the issue yesterday in the PR:
https://github.com/microsoft/responsible-ai-toolbox/pull/1593
Which was a bug introduced in the previous PR:
https://github.com/microsoft/responsible-ai-toolbox/pull/1562
I will do a new erroranalysis package release as soon as [it's](https://github.com/microsoft/responsible-ai-toolbox/pull/1593) is merged.

**Comment by imatiach-msft** [comment]
Bug has been fixed with merged PR:
https://github.com/microsoft/responsible-ai-toolbox/pull/1593
The fix will be in 0.3.6 release of erroranalysis package.  To get latest, run:
```pip install erroranalysis==0.3.6```
Or similarly just get latest via:
```pip install --upgrade erroranalysis```
