### ISSUE TITLE
[Responsible AI Dashboard] Cohort deletion from cohort settings

### ISSUE THREAD

**Issue by nushib** [microsoft/responsible-ai-toolbox#1703]
**Describe the bug**
It is not possible to delete cohorts from cohort settings.

**To Reproduce**

1. Go to 'Cohort settings'
2. Click on 'delete button for one of the created cohorts (not all)'

**Stack trace**
(index):17 
        
       Uncaught TypeError: Cannot read properties of undefined (reading 'cohort')
    at Gu.onDeleteCohortClick ((index):17:2829054)
    at Uu.onDeleteCohortClick [as onClick] ((index):17:2826443)
    at r._onClick ((index):17:315965)
    at Object.He ((index):17:8352688)
    at Ge ((index):17:8352842)
    at (index):17:8370506
    at xa ((index):17:8370600)
    at _a ((index):17:8371014)
    at (index):17:8376583
    at Oe ((index):17:8452288)

**Expected behavior**
Cohort needs to be disappearing from the list and also from the UI of the rest of the components

**Screenshots**
![image](https://user-images.githubusercontent.com/4303632/189438220-154ad20f-c36b-4df3-826f-0f2140bc061c.png)

**Desktop (please complete the following information):**

- OS: Windows
- Browser: Edgecon
- Python version: 3.9.13
- raiwidgets and responsibleai package versions [e.g. 0.19.0]

To get the package versions please run in your command line:

```
pip show raiwidgets
pip show responsibleai
```
Name: raiwidgets
Version: 0.21.0

Name: responsibleai
Version: 0.21.0

**Additional context**

**Comment by gaugup** [comment]
PR https://github.com/microsoft/responsible-ai-toolbox/pull/1738 should fix this.
