### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by OlivierBinette** [microsoft/responsible-ai-toolbox#1853]
**Describe the bug**
The following links are broken.

**In the README:**
- https://github.com/microsoft/responsible-ai-toolbox-genbit

**In https://github.com/microsoft/responsible-ai-toolbox/blob/main/docs/fairness-dashboard-README.md:**
- https://github.com/microsoft/responsible-ai-toolbox/blob/main/notebooks/fairness-dashboard-loan-allocation.ipynb
- https://github.com/microsoft/responsible-ai-toolbox/blob/main/notebooks/fairness-interpretability-dashboard-loan-allocation.ipynb

**Comment by gaugup** [comment]
@OlivierBinette I see the link https://github.com/microsoft/responsible-ai-toolbox-genbit working for me in the main readme. Could you confirm if this link works for you?

I created the PR https://github.com/microsoft/responsible-ai-toolbox/pull/1863 for fixing the links in the fairness docs.
