### ISSUE TITLE
[Error Analysis] Treemap form/layout adjustment

### ISSUE THREAD

**Issue by HyemiSong** [microsoft/responsible-ai-toolbox#223]
Treemap form/layout should be adjusted. They require pixel adjustment iterations in the real env. Please work with Hyemi.

<img width="1436" alt="Screen Shot 2020-12-18 at 2 52 20 PM" src="https://user-images.githubusercontent.com/1608824/102668409-b4aed080-4140-11eb-93fb-9d009e8f1d9e.png">

<img width="799" alt="Screen Shot 2020-12-18 at 2 33 25 PM" src="https://user-images.githubusercontent.com/1608824/102668090-e96e5800-413f-11eb-9af5-cb172f5f3c72.png">

**Comment by imatiach-msft** [comment]
closing as github issues are external only
