### ISSUE TITLE
[Error Analysis] Treemap > pill for filters > Width length limit

### ISSUE THREAD

**Issue by HyemiSong** [microsoft/responsible-ai-toolbox#229]
Since a very long filter name exists, we should apply the width limit for the pill size.
Ellipsis is necessary.

<img width="829" alt="Screen Shot 2020-12-18 at 7 26 15 PM" src="https://user-images.githubusercontent.com/1608824/102679752-e76bbf80-4166-11eb-9975-e99da00f6a8e.png">

**Comment by imatiach-msft** [comment]
closing as github issues are external only
