### ISSUE TITLE
[Error Analysis] The global area > all labels > top bottom centering, Text size/Weight are wrong

### ISSUE THREAD

**Issue by HyemiSong** [microsoft/responsible-ai-toolbox#230]
1.
Top button centering

<img width="1436" alt="Screen Shot 2020-12-18 at 7 51 38 PM" src="https://user-images.githubusercontent.com/1608824/102680128-73cbb180-416a-11eb-81fb-712f11510f1a.png">

2
Text and label size and weight > Please refer to the figma file and the Azure guideline.
1) Error explorer : fontsize > 18

<img width="710" alt="Screen Shot 2020-12-18 at 7 54 07 PM" src="https://user-images.githubusercontent.com/1608824/102680169-cc9b4a00-416a-11eb-8963-09a77b2d1934.png">

**Comment by imatiach-msft** [comment]
closing as github issues are external only
