### ISSUE TITLE
[Error Analysis] Add drop shadow effect to Tooltip UI.

### ISSUE THREAD

**Issue by HyemiSong** [microsoft/responsible-ai-toolbox#231]
It is too flat to distinguish it from the bg. If you cannot find a guideline for drop shadow, please let Hyemi know.

<img width="670" alt="Screen Shot 2020-12-18 at 8 00 01 PM" src="https://user-images.githubusercontent.com/1608824/102680274-a033fd80-416b-11eb-95f6-876a936af038.png">

**Comment by imatiach-msft** [comment]
closing as github issues are external only
