### ISSUE TITLE
[Error Analysis] Heatmap layout tuning

### ISSUE THREAD

**Issue by HyemiSong** [microsoft/responsible-ai-toolbox#234]
Please refer to the figma file to see the detailed pixel.

[Normal]
<img width="926" alt="Screen Shot 2020-12-20 at 9 10 24 PM" src="https://user-images.githubusercontent.com/1608824/102741719-f8a00200-4307-11eb-8f56-57a190c55785.png">
[Fullscreen]
<img width="933" alt="Screen Shot 2020-12-20 at 9 10 34 PM" src="https://user-images.githubusercontent.com/1608824/102741724-f9d12f00-4307-11eb-9a79-12805a319ba0.png">

**Comment by imatiach-msft** [comment]
closing as github issues are external only
