### ISSUE TITLE
[Error Analysis] Heatmap label display- numeric (single/binning)

### ISSUE THREAD

**Issue by HyemiSong** [microsoft/responsible-ai-toolbox#235]
[Unit]
<img width="879" alt="Screen Shot 2020-12-20 at 9 18 20 PM" src="https://user-images.githubusercontent.com/1608824/102742108-f8543680-4308-11eb-8fc6-636b883ca467.png">

[label]
<img width="912" alt="Screen Shot 2020-12-20 at 11 26 22 PM" src="https://user-images.githubusercontent.com/1608824/102750515-c77cfd00-431a-11eb-98db-c74c1ef6322c.png">

**Comment by imatiach-msft** [comment]
closing as github issues are external only
