### ISSUE TITLE
[Error Analysis] Heatmap label display- categorical (single/binning)

### ISSUE THREAD

**Issue by HyemiSong** [microsoft/responsible-ai-toolbox#236]
[Unit]
<img width="879" alt="Screen Shot 2020-12-20 at 9 18 20 PM" src="https://user-images.githubusercontent.com/1608824/102742147-14f06e80-4309-11eb-92d7-bdd8d9a86343.png">

[Single feature]
If the num of features is less than the max num of square cells, it shows individual features.
<img width="818" alt="Screen Shot 2020-12-20 at 11 24 53 PM" src="https://user-images.githubusercontent.com/1608824/102750680-17f45a80-431b-11eb-8778-647ee66179d5.png">

[Binning]
If the num of features is more than the max num of square cells, it shows grouped features.

<img width="797" alt="Screen Shot 2020-12-20 at 11 24 00 PM" src="https://user-images.githubusercontent.com/1608824/102750582-eda29d00-431a-11eb-8ff7-3d36b1d49411.png">
<img width="910" alt="Screen Shot 2020-12-20 at 11 24 15 PM" src="https://user-images.githubusercontent.com/1608824/102750588-f09d8d80-431a-11eb-82a9-20eecc78840f.png">

**Comment by imatiach-msft** [comment]
closing as github issues are external only
