### ISSUE TITLE
[Error Analysis] Explanation layout tuning

### ISSUE THREAD

**Issue by HyemiSong** [microsoft/responsible-ai-toolbox#237]
The overall layout looks not good. Especially, margins around tabs and inspect btn are strange. Please work with Hyemi.

<img width="1435" alt="Screen Shot 2020-12-20 at 11 30 26 PM" src="https://user-images.githubusercontent.com/1608824/102750906-96e99300-431b-11eb-8f98-b426c94846ef.png">

**Comment by imatiach-msft** [comment]
closing as github issues are external only
