### ISSUE TITLE
[Error Analysis] Cohort name (N-filters) + Filter display in the info panel

### ISSUE THREAD

**Issue by HyemiSong** [microsoft/responsible-ai-toolbox#248]
This is the response to the discussion that we had about the cohort name representation.
1. The filters are all filters that you added to the raw data, not you temporarily added.
2. "Save as a new cohort" is displayed after "Cohort: cohort name (N-filters)
3. "Save cohort" option is removed from the Cohort setting because this function is not related to the setting.
4. All temp filter names in the information panel can be displayed (or, displaying only under 5). The text line limit is 2. If it is exceeded, Ellipsis is shown.

<img width="789" alt="Screen Shot 2020-12-21 at 11 22 00 PM" src="https://user-images.githubusercontent.com/1608824/102860929-a207f600-43e3-11eb-814e-3dd4ac40ffdd.png">
<img width="827" alt="Screen Shot 2020-12-21 at 11 22 42 PM" src="https://user-images.githubusercontent.com/1608824/102860931-a3392300-43e3-11eb-8253-4c556a345d7b.png">
<img width="827" alt="Screen Shot 2020-12-21 at 11 22 50 PM" src="https://user-images.githubusercontent.com/1608824/102860937-a502e680-43e3-11eb-8d60-3f7004e04ebf.png">
<img width="827" alt="Screen Shot 2020-12-21 at 11 22 57 PM" src="https://user-images.githubusercontent.com/1608824/102860945-a6ccaa00-43e3-11eb-9e9b-592e6296bef1.png">
<img width="834" alt="Screen Shot 2020-12-21 at 11 23 06 PM" src="https://user-images.githubusercontent.com/1608824/102860952-a8966d80-43e3-11eb-819d-1426490e9725.png">
<img width="836" alt="Screen Shot 2020-12-21 at 11 23 12 PM" src="https://user-images.githubusercontent.com/1608824/102860960-aa603100-43e3-11eb-9f8d-bf5e1ae60cd2.png">
<img width="827" alt="Screen Shot 2020-12-21 at 11 23 16 PM" src="https://user-images.githubusercontent.com/1608824/102860971-ad5b2180-43e3-11eb-872a-f41e8efdb9dd.png">

**Comment by imatiach-msft** [comment]
closing as github issues are external only
