### ISSUE TITLE
[Error Analysis] Save as a new cohort

### ISSUE THREAD

**Issue by HyemiSong** [microsoft/responsible-ai-toolbox#249]
Save cohort is changed to Save as a new cohort to clarify the context.
The modal has "All filters history" btn along with the updated cohort info panel.

<img width="836" alt="Screen Shot 2020-12-21 at 11 33 37 PM" src="https://user-images.githubusercontent.com/1608824/102861940-3888e700-43e5-11eb-92f3-80d8b0329845.png">
<img width="838" alt="Screen Shot 2020-12-21 at 11 33 43 PM" src="https://user-images.githubusercontent.com/1608824/102861944-3a52aa80-43e5-11eb-8538-46fe94d4e9bf.png">

**Comment by imatiach-msft** [comment]
closing as github issues are external only
