### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by 456ke** [microsoft/responsible-ai-toolbox#2506]
**Describe the bug**

**To Reproduce**

**Stack trace**
If applicable, please add the sdk stack trace for the error.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- Python version: [e.g. 3.9.12]
- raiwidgets and responsibleai package versions [e.g. 0.19.0]

To get the package versions please run in your command line:

```
pip show raiwidgets
pip show responsibleai
```

**Additional context**

**Comment by imatiach-msft** [comment]
closing as I don't see any description
