### ISSUE TITLE
Copying content will result in a blank page

### ISSUE THREAD

**Issue by wadeKings** [microsoft/responsible-ai-toolbox#2575]
**Describe the bug**
Copying content will result in a blank page

**To Reproduce**

1. Go to 'https://github.com/microsoft/responsible-ai-toolbox/blob/main/notebooks/responsibleaidashboard/tabular/getting-started.ipynb'
2. Copy the any contents of the ipynb file

**Expected behavior**
context is copied

**Screenshots**
![image](https://github.com/user-attachments/assets/f55b0865-69b7-4c9c-888b-a7d5ba8ba327)

**Desktop (please complete the following information):**

- OS: Windows11 home
- Browser edge

**Comment by imatiach-msft** [comment]
@wadeKings can you please try to download the file using the button like below?
![image](https://github.com/user-attachments/assets/372eef1e-89c4-41b5-ae79-e852152d8e6a)
otherwise, this doesn't look like an issue with the repository but more an issue with github if I understand correctly?
