### ISSUE TITLE
Wells Fargo

### ISSUE THREAD

**Issue by chris6090** [microsoft/responsible-ai-toolbox#2583]
**Describe the bug**

**To Reproduce**

**Stack trace**
If applicable, please add the sdk stack trace for the error.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- Python version: [e.g. 3.9.12]
- raiwidgets and responsibleai package versions [e.g. 0.19.0]

To get the package versions please run in your command line:

```
pip show raiwidgets
pip show responsibleai
```

**Additional context**
Add any other context about the problem here.[![image](https://github.com/user-attachments/assets/063fde07-a24f-4b00-930e-bb499d84c867)]()

**Comment by imatiach-msft** [comment]
@chris6090 sorry I did not understand the question. also this github is public please don't post your private info here.
