### ISSUE TITLE
[Error Analysis] Modal and Panel guidlines

### ISSUE THREAD

**Issue by HyemiSong** [microsoft/responsible-ai-toolbox#259]
Along with the new requested design, the last design version (ver 1.1) includes UI guidelines for modal and panel. Please take a look at the section.

Ver 1.1
https://www.figma.com/file/2WAj63Te9lEAswZeubHAm7/?node-id=4375%3A6161

<img width="942" alt="Screen Shot 2021-01-01 at 7 24 31 PM" src="https://user-images.githubusercontent.com/1608824/103450174-4bae7900-4c67-11eb-9d9f-264d2ce580d6.png">

**Comment by imatiach-msft** [comment]
closing as github issues are external only
