### ISSUE TITLE
Hello, please find the documentation for the new Opik integration https://github.com/langgenius/dify/issues/11407. I had three questions while working on this PR:

### ISSUE THREAD

**Issue by loganclark360** [microsoft/responsible-ai-toolbox#2591]
Hello, please find the documentation for the new Opik integration https://github.com/langgenius/dify/issues/11407. I had three questions while working on this PR:

* Is there a way to generate the docs locally to check that everything looks good? I tried `gitbook serve .` but it renders an almost empty website.
* I updated the screenshot `en/.gitbook/assets/tracing-app-performance.png` to include the new Opik tracker but with a lower resolution, is that a problem?
* I have seen the translation script, is it called automatically or should I call it myself?

Thanks

_Originally posted by @Lothiraldan in https://github.com/langgenius/dify-docs/pull/395_

**Comment by imatiach-msft** [comment]
this looks like the wrong repository for the question
