### ISSUE TITLE
Error Analysis and Interpretability Scalability Design Decisions

### ISSUE THREAD

**Issue by mesameki** [microsoft/responsible-ai-toolbox#279]
Issue: Error analysis heatmap and treemap views can be calculated on very large datasets. Interpretabiliy, however, downsamples to 5K and only generates that many local explanations and render them in the UI. This mismatch of scalability capabilities needs to be navigated and addressed in the UI to not limit the error analysis functionalities and features. We discussed the following solution: We will calculate Error analysis tree map and heat map on ALL DATA, but only generate explanations for 5K subsampled dataset. Now, users going thorugh the dashboard can see the following options:
 
 
-- User selects a cohort on the decision tree or selects one of more grids on the heatmap and clicks on “explanation”. Downsampling for explanation can lead to that cohort not having any explanations attached (In an unfortunate situation none of the 5K subsampled dataset covers the cohort datapoints). Solution we chose:

-------> [CHOSEN OPTION] Allow them to click on the explanation tab. But, disable only global and local explanation tabs and let them explore data explorer and ONLY see aggregate insights on all data. Aggregate insights calculations will be kicked off from UI and happen on ALL Data not subsampled data.

 
-- User selects a cohort on the decision tree or selects one of more grids on the heatmap and clicks on “explanation”. Downsampling for explanation can lead to that cohort not having any explanations attached (In an unfortunate situation none of the 5K subsampled dataset covers the cohort datapoints). Solution we chose:

-------> [CHOSEN OPTION] Allow them to click on the explanation tab. But, disable only global and local explanation tabs and let them explore data explorer and ONLY see aggregate insights on all data. Aggregate insights calculations will be kicked off from UI and happen on ALL Data not subsampled data.

-- User selects a cohort on the decision tree or selects one of more grids on the heatmap and clicks on “explanation”. Downsampling for explanation can lead to that cohort having some explanations attached (explanations generated for the downsampled dataset has some overlap with that cohort datapoints). Solution we chose:

-------> [CHOSEN OPTION] 1. Data explorer will show aggregate insights of all cohort data points of that cohort.
-------> [CHOSEN OPTION] 2. Global explanation will have a warning on top stating that this is overall explanations of the subsampled dataset. (if the explanations are for less than X datapoints, maybe we go with the previous approach of assuming no explanations are there…)
-------> [CHOSEN OPTION] 3. [For end of Jan] local explanation tab only shows the cohorts data points that have explanations.

[In future, not for end of Jan] we would like to expand our UI capabilities to enable on-demand generation of local explanations for a cohort datapoints that user has selected and thus, in the instance view, we can show all individuals of that cohort. Adding pagination capabilities to our instance table to expand it at scale [Using AP as our role model].

**Comment by imatiach-msft** [comment]
for warning message, add: "for scale reasons of the UI, explanations are randomly subsampled down to <5k datapoints"

**Comment by imatiach-msft** [comment]
closing as PR https://github.com/microsoft/responsible-ai-toolbox/pull/1098 has been merged and this was the last remaining part of this issue
