### ISSUE TITLE
[Error Analysis]: Data explorer cuts out categories in the x axis

### ISSUE THREAD

**Issue by nushib** [microsoft/responsible-ai-toolbox#318]
How to reproduce:

- set number of classifiers to 50 in lightgbm
- create a cohort using the tree ( see fig below)
- go to data explorer for that cohort and use count by education (see fig below)

![image](https://user-images.githubusercontent.com/4303632/107267728-277b5000-69fc-11eb-80cf-5e5c75b7706c.png)

next

![image](https://user-images.githubusercontent.com/4303632/107267756-2d713100-69fc-11eb-846a-5ee6d60fe1b3.png)

**Comment by imatiach-msft** [comment]
this issue is fixed now after we moved to highcharts, count by education does not cut off the x-axis anymore:

![image](https://user-images.githubusercontent.com/24683184/172484491-ae9c4002-7cf0-455b-b58a-42a19043d2e1.png)
