### ISSUE TITLE
some notebook for loading from torch?

### ISSUE THREAD

**Issue by finardi** [microsoft/responsible-ai-toolbox#568]
Hi, thanks for this amazing tool. 

I would suggest a notebook that carries a trained torch model. I'm trying to use a Census dataset from a trained pytorch model with a simple MLP and I'm not getting / knowing how to do.

**Comment by gaugup** [comment]
@finardi, which tool are you referring to? This repo has erroanalysis, responsibleai and raiwidgets. 

I know responsibleai doesn't support torch models as yet. I can find about raiwidgets and erroranalysis.

Regards,

**Comment by imatiach-msft** [comment]
closing this issue as an example notebook has been added for how to use pytorch with the RAI dashboard
